use exif::Tag;

pub struct TagLabelMaps {
    pub camera_tag_map: Vec<(Tag, &'static str)>,
    pub lens_tag_map: Vec<(Tag, &'static str)>,
    pub image_tag_map: Vec<(Tag, &'static str)>,
    pub other_tag_map: Vec<(Tag, &'static str)>,
}

impl TagLabelMaps {
    pub fn get() -> TagLabelMaps {
        TagLabelMaps {
            camera_tag_map: vec![
                (Tag::Make, "Maker"),
                (Tag::Model, "Model"),
                (Tag::Software, "Software"),
                (Tag::BodySerialNumber, "Serial Number"),
                (Tag::CameraOwnerName, "Owner Name"),
            ],
            lens_tag_map: vec![
                (Tag::LensMake, "Maker"),
                (Tag::LensModel, "Model"),
                (Tag::LensSpecification, "Specs"),
                (Tag::LensSerialNumber, "Serial Number"),
            ],
            image_tag_map: vec![
                (Tag::ExposureTime, "Exposure Time"),
                (Tag::ApertureValue, "Aperture"),
                (Tag::BrightnessValue, "Brightness"),
                (Tag::Contrast, "Contrast"),
                (Tag::FocalLength, "Focal Length"),
            ],
            other_tag_map: vec![
                (Tag::Acceleration, "Acceleration"),
                (Tag::Artist, "Artist"),
                (Tag::BitsPerSample, "Bits/sample"),
                (Tag::CameraElevationAngle, "Elevation Angle"),
                (Tag::CFAPattern, "CFA Pattern"),
                (Tag::ColorSpace, "Color Space"),
                (Tag::ComponentsConfiguration, "Components Configuration"),
                (Tag::CompressedBitsPerPixel, "Compressed Bits/Pixel"),
                (Tag::CustomRendered, "Custom Rendered"),
                (Tag::DateTime, "Date & time"),
                (Tag::DateTimeOriginal, "Date Time Original"),
                (Tag::DateTimeDigitized, "Date Time Digitized"),
                (Tag::DeviceSettingDescription, "Device Setting Description"),
                (Tag::DigitalZoomRatio, "Digital Zoom Ratio"),
                (Tag::ExifVersion, "EXIF Version"),
                (Tag::FileSource, "File Source"),
                (Tag::Flash, "Flash"),
                (Tag::FlashEnergy, "Flash Energy"),
                (Tag::FocalPlaneXResolution, "Focal Plane X Resolution"),
                (Tag::FocalPlaneYResolution, "Focal Plane Y Resolution"),
                (Tag::GainControl, "Gain Control"),
                (Tag::GPSLatitude, "GPS Latitude"),
                (Tag::GPSLongitude, "GPS Longitude"),
                (Tag::GPSAltitude, "GPS Altitude"),
                (Tag::ImageDescription, "Image Description"),
                (Tag::InteroperabilityIndex, "Interoperability Index"),
                (Tag::ISOSpeed, "ISO Speed Ratings"),
                (Tag::ISOSpeedLatitudeyyy, "ISO Speed Latitude Y"),
                (Tag::ISOSpeedLatitudezzz, "ISO Speed Latitude Z"),
                (Tag::LightSource, "Light Source"),
                (Tag::MeteringMode, "Metering Mode"),
                (Tag::Orientation, "Orientation"),
                (Tag::PhotometricInterpretation, "Photometric Interpretation"),
                (Tag::SpatialFrequencyResponse, "Spatial Frequency Response"),
                (Tag::SubjectArea, "Subject Area"),
                (Tag::GPSDOP, "GPS DOP"),
                (Tag::GPSSpeed, "GPS Speed"),
                (Tag::Compression, "Compression"),
                (Tag::ImageWidth, "Image Width"),
                (Tag::ImageLength, "Image Length"),
                (Tag::SamplesPerPixel, "Samples per Pixel"),
                (Tag::PlanarConfiguration, "Planar Configuration"),
                (Tag::YCbCrSubSampling, "Chrominance Subsampling"),
                (Tag::XResolution, "X Resolution"),
                (Tag::YResolution, "Y Resolution"),
                (Tag::ResolutionUnit, "Resolution Unit"),
                (Tag::StripOffsets, "Strip Offsets"),
                (Tag::RowsPerStrip, "Rows per Strip"),
                (Tag::StripByteCounts, "Strip Byte Counts"),
                (Tag::JPEGInterchangeFormat, "JPEG Interchange Format"),
                (Tag::JPEGInterchangeFormatLength, "JPEG Interchange Format Length"),
                (Tag::TransferFunction, "Transfer Function"),
                (Tag::WhitePoint, "White Point"),
                (Tag::PrimaryChromaticities, "Primary Chromaticities"),
                (Tag::YCbCrCoefficients, "Chrominance Coefficients"),
                (Tag::YCbCrPositioning, "Chrominance Positioning"),
                (Tag::ReferenceBlackWhite, "Black/White References"),
            ]
        }
    }
}